import { ApiError } from './types.ts';
import type { Model, Request, Role, Retirement, Impact } from './types.ts';
export interface Job { id:string; name:string; schedule:string; owner:string; status:'SUCCESS'|'PARTIAL'|'FAILED'; at:string; success:number; failed:number; logs:string[]; rerunnable:boolean }
export interface Source { id:string; name:string; input:string; output:string; excerpt:string; collectedAt:string }
export interface Staging { id:string; modelId:string; sku:string; confidence:number; status:'PENDING'|'CONFIRMED'|'DISCARDED'; sources:Source[]; actor?:string; reason?:string; at?:string; changeId?:string }
export interface Step { role:Role|null; label:string; by?:string; at?:string }
export interface Change { financialPreview?: { component:string; beforeCost:string; afterCost:string; sale:string; beforeMargin:string; afterMargin:string }[] }
export interface Change { id:string; modelId:string; sku:string; type:'PRICE_UP'|'PRICE_DOWN'|'DEPRECATE'; status:'APPROVING'|'APPROVED'|'EFFECTIVE'|'REJECTED'; before:string; after:string; outputBefore:string; outputAfter:string; reason:string; steps:Step[]; impact:Impact|null; suppliers:string[]; trace:string[]; offlineAt?:string; sourceId?:string }
export interface AlertItem { id:string; title:string; severity:string; status:'OPEN'|'HANDLED'|'TRANSFERRED'; owner:string; note:string; at:string }
export interface Todo { id:string; title:string; kind:string; owner:string; path:string }
export interface Activity { at:string; text:string }
export interface Workbench { metrics:{label:string;value:number;hint:string}[]; todos:Todo[]; alerts:AlertItem[]; activities:Activity[] }
const people:Record<Role,string>={MODEL_OPS:'林悦 · 模型运营',PRICING_OP:'周婷 · 定价运营',VIEWER:'只读观察员'};
const definitions=[
 ['sync-models','厂商模型清单同步','每日 03:00'],['sync-prices','官方价格采集','每日 04:00 / 事件触发'],['sync-community','社区价格交叉校验','每日 05:00'],['sync-diff','暂存价格差异比对','采集后执行'],['cost-recalc-daily','每日成本基线重算','每日 06:00'],['quote-expire-scan','供应商报价到期预警','每日 07:00'],['quote-expire-final','到期报价确认剔除','每日 07:10'],['quote-anomaly-scan','供应商报价异常扫描','每日 07:20'],['fx-remind','汇率锁定提醒','每月 1 日 09:00'],['qual-expire-scan','供应商资质到期检查','每日 08:00'],['credit-scan','授信与押金核对','每日 08:30'],['quote-activate','预约报价生效','每分钟'],['price-book-activate','预约价目表生效','每分钟'],['customer-quote-expire','临时客户报价到期处理','每日 07:30'],['session-sweep','过期登录会话清理','每小时'],['idem-sweep','过期幂等记录清理','每日 02:00'],['event-push','业务事件通知推送','每 10 秒'],['report-retro','特权补录月报生成','每月 1 日 10:00']
];
const now=()=>new Date().toISOString();
const amount=(value:string)=>{if(!/^\d+(\.\d{1,8})?$/.test(value))throw new ApiError(422,'金额必须是最多八位小数的非负字符串');const [a,b='']=value.split('.');return BigInt(a!)*100000000n+BigInt(b.padEnd(8,'0'));};
export function createOperations(getModels:()=>Model[],getRetirements:()=>Retirement[],getReport:(id:string)=>Impact|undefined){
 let jobs:Job[]=[],staging:Staging[]=[],changes:Change[]=[],alerts:AlertItem[]=[],activities:Activity[]=[];let counter=100;
 const keys=new Map<string,{signature:string;result:unknown}>();
 const log=(text:string)=>activities.unshift({at:now(),text});
 const findChange=(id:string)=>{const c=changes.find(c=>c.id===id);if(!c)throw new ApiError(404,'变更单不存在');return c;};
 const visible=(c:Change,role:Role)=>{const result=structuredClone(c);if(role==='PRICING_OP'&&c.type!=='DEPRECATE'){const fmt=(n:bigint)=>`${n/100000000n}.${String(n%100000000n).padStart(8,'0')}`;result.financialPreview=[['输入',c.before,c.after],['输出',c.outputBefore,c.outputAfter]].map(([component,before,after])=>{const b=amount(before!)*8n/10n,a=amount(after!)*8n/10n,sale=b*2n;return {component:component!,beforeCost:fmt(b),afterCost:fmt(a),sale:fmt(sale),beforeMargin:sale?'50.00%':'—',afterMargin:sale?`${(sale-a)*10000n/sale/100n}.${String(((sale-a)*10000n/sale)%100n).replace('-','').padStart(2,'0')}%`:'—'};});}return result;};
 function reset(){counter=100;keys.clear();jobs=definitions.map(([id,name,schedule],i)=>({id:id!,name:name!,schedule:schedule!,owner:i<4?'模型运营 / 运维':'运维队列',status:i===2?'FAILED':i===1?'PARTIAL':'SUCCESS',at:now(),success:i===2?0:12,failed:i===2?3:i===1?1:0,logs:i===2?['演示：社区页面结构变化，解析失败。','保留上次有效价格，等待运维修复采集规则。']:i===1?['演示：12 条成功，1 条来源超时。','失败对象：Claude Sonnet 4 定价页；已转运维队列。']:['演示：任务已完成，无异常。'],rerunnable:i<4}));
 const models=getModels();staging=[0,1,2].map((index)=>{const m=models[index]!;return {id:`ST-${index+1}`,modelId:m.id,sku:m.code,confidence:[96,58,77][index]!,status:'PENDING',sources:[{id:'official',name:'官方定价页 · 演示摘录',input:index===0?'2.50000000':index===1?'0.30000000':'3.50000000',output:m.output,excerpt:`${m.name} 输入价格 / 百万 token。该文本为模拟审核材料，不是实时采集证据。`,collectedAt:now()},{id:'community',name:'社区对照源 · 演示摘录',input:index===1?'0.35000000':index===0?'2.50000000':'3.80000000',output:m.output,excerpt:'非官方对照资料存在差异，需人工确认适用型号、价格单位与币种。',collectedAt:now()}]};});
 changes=[{id:'CR-DEMO-UP',modelId:models[2]!.id,sku:models[2]!.code,type:'PRICE_UP',status:'APPROVING',before:models[2]!.input,after:'3.50000000',outputBefore:models[2]!.output,outputAfter:models[2]!.output,reason:'官方涨价演示',steps:[{role:'MODEL_OPS',label:'模型运营'},{role:'PRICING_OP',label:'定价运营'}],impact:null,suppliers:['云桥科技（倍率报价）','星河算力（绝对价，不自动跟随）'],trace:[]}];
 alerts=[{id:'AL-1',title:'社区采集失败，原有效价格已保留',severity:'高',status:'OPEN',owner:'运维队列',note:'请检查采集规则与来源可用性',at:now()}];activities=[{at:now(),text:'演示工作空间已就绪'}]; }
 function syncRetirements(){for(const r of getRetirements()){if(changes.some(c=>c.id===r.id))continue;const m=getModels().find(m=>m.id===r.modelId);if(!m)continue;changes.push({id:r.id,modelId:m.id,sku:m.code,type:'DEPRECATE',status:'APPROVING',before:m.input,after:m.input,outputBefore:m.output,outputAfter:m.output,reason:r.reason,steps:[{role:'PRICING_OP',label:'定价运营'},{role:null,label:'第二审批人待配置'}],impact:structuredClone(getReport(r.id)||null),offlineAt:r.offlineAt,suppliers:[],trace:[]});log(`${m.code} 退役申请进入定价运营待办`);}}
 function todos(role:Role):Todo[]{const list:Todo[]=[];if(role==='MODEL_OPS'){for(const s of staging.filter(s=>s.status==='PENDING'))list.push({id:s.id,title:`确认 ${s.sku} 官方价格`,kind:'价格审核',owner:'模型运营',path:`/sync?tab=staging&id=${s.id}`});const pending=getModels().filter(m=>m.status==='PENDING_VERIFY');if(pending.length)list.push({id:'verify',title:`${pending.length} 个模型等待人工验证`,kind:'模型验证',owner:'模型运营',path:'/models'});}for(const c of changes.filter(c=>c.status==='APPROVING')){const step=c.steps.find(s=>!s.by);if(step?.role===role)list.push({id:c.id,title:`${c.type==='DEPRECATE'?'退役':c.type==='PRICE_UP'?'涨价':'降价'}审批 · ${c.sku}`,kind:'变更审批',owner:step.label,path:`/sync?tab=changes&id=${c.id}`});}return list;}
 reset();
 function handle(req:Request):unknown {syncRetirements();const body=(req.body||{}) as Record<string,string>;const write=req.method!=='GET';const signature=JSON.stringify([req.method,req.path,req.body]);const key=`${req.role}:${req.key}`;
 if(write){if(req.role==='VIEWER')throw new ApiError(403,'当前身份只能查看');if(!req.key)throw new ApiError(400,'缺少幂等键');const prev=keys.get(key);if(prev){if(prev.signature!==signature)throw new ApiError(409,'幂等键冲突');return structuredClone(prev.result);}}
 let result:unknown;
 if(req.path==='/api/internal/workbench/metrics'&&!write){const mine=todos(req.role);result={metrics:[{label:'我的待办',value:mine.length,hint:'按当前演示角色聚合'},{label:'待审核价格',value:staging.filter(s=>s.status==='PENDING').length,hint:'待人工核对来源'},{label:'待审批变更',value:changes.filter(c=>c.status==='APPROVING').length,hint:'包含退役审批'},{label:'任务异常',value:jobs.filter(j=>j.status!=='SUCCESS').length,hint:'失败 / 部分成功'}],todos:mine,alerts,activities:activities.slice(0,12)} satisfies Workbench;}
 else if(req.path==='/api/internal/sync/jobs'){if(!write)result=jobs;else{if(req.role!=='MODEL_OPS')throw new ApiError(403,'采集重跑仅限模型运营');const j=jobs.find(j=>j.id===body.id);if(!j||!j.rerunnable)throw new ApiError(403,'该任务由运维维护，此页面仅支持采集任务重跑');j.at=now();j.status='SUCCESS';j.success=13;j.failed=0;j.logs.unshift('模拟重跑成功；未联网采集、未修改生产价格。');log(`${j.name} 手动重跑完成`);result=j;}}
 else if(req.path==='/api/internal/sync/staging'&&!write)result=staging;
 else if(req.path.startsWith('/api/internal/sync/staging/')&&write){if(req.role!=='MODEL_OPS')throw new ApiError(403,'仅模型运营可裁定暂存价格');const id=req.path.split('/').at(-2);const s=staging.find(s=>s.id===id);if(!s)throw new ApiError(404,'暂存记录不存在');if(s.status!=='PENDING')throw new ApiError(409,'该记录已处理');if(!body.reason?.trim())throw new ApiError(422,'请填写审核依据或丢弃理由');if(req.path.endsWith('/discard')){s.status='DISCARDED';log(`${s.sku} 暂存价格已丢弃`);}else if(req.path.endsWith('/confirm')){const source=s.sources.find(x=>x.id===body.sourceId);if(!source)throw new ApiError(422,'请选择采用的数据来源');const m=getModels().find(m=>m.id===s.modelId)!;const inputDelta=amount(source.input)-amount(m.input),outputDelta=amount(source.output)-amount(m.output);if(inputDelta===0n&&outputDelta===0n)throw new ApiError(422,'该来源与当前价格一致，无需生成变更单，可填写理由丢弃');const up=inputDelta>0n||outputDelta>0n;const c:Change={id:`CR-${++counter}`,modelId:m.id,sku:m.code,type:up?'PRICE_UP':'PRICE_DOWN',status:'APPROVING',before:m.input,after:source.input,outputBefore:m.output,outputAfter:source.output,reason:body.reason,steps:up?[{role:'MODEL_OPS',label:'模型运营'},{role:'PRICING_OP',label:'定价运营'}]:[{role:'MODEL_OPS',label:'模型运营'}],impact:null,suppliers:['云桥科技（倍率报价）','星河算力（绝对价，不自动跟随）'],trace:[`${people[req.role]} 采用 ${source.name}`],sourceId:s.id};changes.push(c);s.status='CONFIRMED';s.changeId=c.id;log(`${s.sku} 已确认并生成 ${c.id}`);}else throw new ApiError(404,'操作不存在');s.reason=body.reason;s.actor=people[req.role];s.at=now();result=s;}
 else if(req.path==='/api/internal/change-requests'&&!write)result=changes.map(c=>visible(c,req.role));
 else if(req.path.startsWith('/api/internal/change-requests/')&&write){const action=req.path.split('/').at(-1);const c=findChange(req.path.split('/').at(-2)!);const m=getModels().find(m=>m.id===c.modelId)!;
 if(action==='activate'){if(req.role!=='PRICING_OP'&&!(req.role==='MODEL_OPS'&&c.type==='PRICE_DOWN'))throw new ApiError(403,'无此变更生效权限');if(c.status!=='APPROVED'||c.type==='DEPRECATE')throw new ApiError(409,'当前单据不能模拟生效');if(m.input!==c.before||m.output!==c.outputBefore)throw new ApiError(409,'当前价格已变化，请重新生成变更单');m.input=c.after;m.output=c.outputAfter;c.status='EFFECTIVE';c.trace.push('Mock 官方价格已更新；成本重算、价目表冻结及通知尚未实现');log(`${c.sku} 官方价格已模拟生效`);}
 else if(action==='approve'||action==='reject'){if(c.status!=='APPROVING')throw new ApiError(409,'当前单据不在审批中');const step=c.steps.find(s=>!s.by);if(!step?.role)throw new ApiError(409,'第二审批人尚未配置，不能继续审批');if(step.role!==req.role)throw new ApiError(403,`当前应由${step.label}处理`);if(!body.reason?.trim())throw new ApiError(422,'请填写审批意见');if(action==='reject'){c.status='REJECTED';if(c.type==='DEPRECATE')m.pendingRetirement=false;c.trace.push(`${people[req.role]} 驳回：${body.reason}`);log(`${c.sku} 变更已驳回，原数据保留`);}else{if(body.reviewed!=='yes')throw new ApiError(422,'请先阅读影响材料并确认');step.by=people[req.role];step.at=now();c.trace.push(`${step.by} 审批通过：${body.reason}`);if(c.steps.every(s=>s.by)){c.status='APPROVED';log(`${c.sku} ${c.steps.length===1?'单人':'双人'}审批通过，等待模拟生效`);}else log(`${c.sku} 已完成第一签，转交 ${c.steps.find(s=>!s.by)!.label}`);}}else throw new ApiError(404,'操作不存在');result=visible(c,req.role);}
 else if(req.path==='/api/internal/alerts'&&write){if(req.role!=='MODEL_OPS')throw new ApiError(403,'当前演示仅模型运营可处理采集告警');const a=alerts.find(a=>a.id===body.id);if(!a)throw new ApiError(404,'告警不存在');if(a.status!=='OPEN')throw new ApiError(409,'告警已处理');if(!body.note?.trim())throw new ApiError(422,'请填写处理说明');if(!['handle','transfer'].includes(body.action))throw new ApiError(422,'操作不支持');a.status=body.action==='transfer'?'TRANSFERRED':'HANDLED';a.owner=body.action==='transfer'?'运维待办队列':people[req.role];a.note=body.note;log(`${a.title}：${a.status==='TRANSFERRED'?'已转运维待办队列':'已标记处理'}`);result=a;}
 else throw new ApiError(404,'演示接口不存在');if(write)keys.set(key,{signature,result:structuredClone(result)});return structuredClone(result);
 }
 return {handle,reset};
}
