export const PERMISSIONS = {
  MODEL_VIEW: "M1:V",
  MODEL_EDIT: "M1:E",
  MODEL_APPROVE: "M1:A",
  PRICE_SYNC_VIEW: "M2:V",
  PRICE_SYNC_EDIT: "M2:E",
  PRICE_SYNC_APPROVE: "M2:A",
  SUPPLIER_VIEW: "M3:V",
  SUPPLIER_EDIT: "M3:E",
  SUPPLIER_APPROVE: "M3:A",
  SUPPLIER_QUOTE_VIEW: "M4:V",
  SUPPLIER_QUOTE_APPROVE: "M4:A",
  SUPPLIER_QUOTE_EDIT: "M4:E",
  SUPPLIER_QUOTE_PRIVILEGE: "M4:P",
  COST_VIEW: "M5:V",
  COST_EDIT: "M5:E",
  PRICING_POLICY_VIEW: "M6:V",
  PRICING_POLICY_EDIT: "M6:E",
  PRICE_BOOK_VIEW: "M7:V",
  PRICE_BOOK_EDIT: "M7:E",
  PRICE_BOOK_APPROVE: "M7:A",
  CUSTOMER_VIEW: "M8:V",
  CUSTOMER_EDIT: "M8:E",
  CUSTOMER_QUOTE_VIEW: "M9:V",
  CUSTOMER_QUOTE_EDIT: "M9:E",
  CUSTOMER_QUOTE_APPROVE: "M9:A",
  FINANCE_VIEW: "M10:V",
  FINANCE_EDIT: "M10:E",
  ORG_PERMISSION_VIEW: "M11:V",
  ORG_PERMISSION_CONFIGURE: "M11:C",
  AUDIT_VIEW: "M12:V",
  ALERT_VIEW: "M13:V",
  ALERT_HANDLE: "M13:E",
} as const;

export type PermissionCode =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROUTE_REQUIREMENTS: Record<string, PermissionCode | null> = {
  "internal.workbench": null,
  "internal.models": PERMISSIONS.MODEL_VIEW,
  "internal.modelApplications": PERMISSIONS.MODEL_VIEW,
  "internal.officialPrices": PERMISSIONS.PRICE_SYNC_VIEW,
  "internal.suppliers": PERMISSIONS.SUPPLIER_VIEW,
  "internal.supplierQuotes": PERMISSIONS.SUPPLIER_QUOTE_VIEW,
  "internal.cost": PERMISSIONS.COST_VIEW,
  "internal.pricingPolicies": PERMISSIONS.PRICING_POLICY_VIEW,
  "internal.priceBooks": PERMISSIONS.PRICE_BOOK_VIEW,
  "internal.customers": PERMISSIONS.CUSTOMER_VIEW,
  "internal.finance": PERMISSIONS.FINANCE_VIEW,
  "internal.alerts": PERMISSIONS.ALERT_VIEW,
  "internal.audit": PERMISSIONS.AUDIT_VIEW,
  "internal.orgPermissions": PERMISSIONS.ORG_PERMISSION_VIEW,
  "internal.integration": PERMISSIONS.AUDIT_VIEW,
  "supplier.home": null,
  "supplier.quotes": null,
  "supplier.quoteNew": null,
  "supplier.quoteImport": null,
  "supplier.modelApplications": null,
  "supplier.profile": null,
  "supplier.qualifications": null,
  "supplier.reconciliation": null,
  "customer.home": null,
  "customer.priceBook": null,
  "customer.quotes": null,
  "customer.contracts": null,
  "customer.billing": null,
  "customer.notifications": null,
};
