import { createRequire } from "node:module";
import assert from "node:assert/strict";
import { createServer } from "vite";
import { readFile } from "node:fs/promises";

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const browser = await chromium.launch({ headless: true, channel: "msedge" });
const errors = [];
let devServer;
async function start(mockEnabled, plugins = []) {
  process.env.VITE_MOCK_ENABLED = String(mockEnabled);
  process.env.VITE_AUTH_ENABLED = "false";
  devServer = await createServer({ server: { host: "127.0.0.1", port: 0 }, plugins, logLevel: "error" });
  await devServer.listen();
  return `http://127.0.0.1:${devServer.httpServer.address().port}`;
}
function track(page) { page.on("pageerror", error => errors.push(error.message)); page.setDefaultTimeout(15000); }
async function identity(page, name) {
  await page.locator(".app-topbar__actions .el-select__wrapper").nth(1).click();
  await page.getByRole("option", { name, exact: true }).click();
}
try {
  const origin = await start(true);
  const context = await browser.newContext();
  const page = await context.newPage(); track(page);
  await page.goto(origin);
  await page.getByRole("heading", { name: "林悦，你好", exact: true }).waitFor();
  await page.goto(`${origin}/#/internal/models`);
  await page.getByRole("heading", { name: "模型管理", exact: true }).waitFor();
  await page.getByRole("button", { name: "gpt-4.1", exact: true }).waitFor();
  assert.ok(await page.getByRole("button", { name: "上架", exact: true }).count() > 0);
  const retiringRow = page.getByRole("row").filter({ has: page.getByRole("button", { name: "claude-haiku-4", exact: true }) });
  await retiringRow.getByRole("button", { name: "发起退役", exact: true }).click();
  await page.getByRole("button", { name: "加载退役影响分析", exact: true }).click();
  await page.getByText("标准价目表 · 演示", { exact: true }).waitFor();
  await page.getByText(/下线日须距通知任务发出日至少30天/).waitFor();
  await page.getByPlaceholder("选择下线日").fill("2099-01-01");
  await page.getByPlaceholder("选择下线日").press("Enter");
  await page.getByRole("dialog").locator("textarea").fill("浏览器核验退役申请，通知与审批分离");
  await page.getByRole("button", { name: "提交退役审批", exact: true }).click();
  await page.locator(".el-message-box").getByRole("button", { name: "确定", exact: true }).click();
  await page.getByText("已提交退役申请", { exact: true }).waitFor();
  await page.getByText(/双人审批通过后才进入即将下线/).waitFor();
  await page.getByRole("button", { name: "返回模型列表", exact: true }).click();
  await retiringRow.getByText("已上架", { exact: true }).waitFor();
  await retiringRow.getByRole("button", { name: "claude-haiku-4", exact: true }).click();
  await page.getByText("退役申请已提交，等待双人审批；模型生命周期尚未改变。", { exact: true }).waitFor();
  await page.getByRole("button", { name: "关闭此对话框", exact: true }).click();
  await identity(page, "周婷 · 定价运营");
  await page.getByRole("button", { name: "上架", exact: true }).first().waitFor();
  await page.goto(`${origin}/#/internal/price-books`);
  await page.getByRole("heading", { name: "价目表", exact: true }).waitFor();
  await page.getByLabel("SKU ID sku_ids（可选）").fill("40, 41");
  await page.getByRole("button", { name: "生成草稿", exact: true }).click();
  await page.getByRole("heading", { name: "草稿生成结果", exact: true }).waitFor();
  await page.getByText("SKU-40", { exact: true }).waitFor();
  await page.getByRole("button", { name: "发布草稿", exact: true }).click();
  await page.getByText("APPROVING", { exact: true }).waitFor();
  await page.getByText("审批顺序：PRICING_OP → FINANCE", { exact: true }).waitFor();
  await page.locator(".app-topbar__actions .el-select__wrapper").first().click();
  await page.getByRole("option", { name: "深色", exact: true }).click();
  assert.equal(await page.locator("html").evaluate(node => node.classList.contains("dark")), true);
  await identity(page, "陈昊 · 采购审批");
  await page.goto(`${origin}/#/internal/supplier-quotes`);
  await page.getByRole("row").filter({ hasText: "星河算力" }).getByRole("button", { name: "查看并审批", exact: true }).click();
  await page.getByRole("button", { name: "通过整单", exact: true }).click();
  await page.getByRole("button", { name: "确认通过", exact: true }).click();
  await page.getByText("已批准，等待后端按计划生效时间激活。", { exact: true }).waitFor();
  await page.getByRole("row").filter({ hasText: "云桥科技" }).getByRole("button", { name: "查看并审批", exact: true }).click();
  await page.getByRole("button", { name: "驳回", exact: true }).click();
  await page.getByPlaceholder("10—500字，说明供应商应如何复核").fill("浏览器验证，请供应商复核价格后重新提交");
  await page.getByRole("button", { name: "确认驳回", exact: true }).click();
  await page.getByText("报价已驳回，原因供应商可见。", { exact: true }).waitFor();
  await page.evaluate(() => { window.location.hash = "#/supplier/quotes"; });
  await page.getByRole("heading", { name: "报价历史", exact: true }).waitFor();
  await page.getByRole("button", { name: "＋ 新建报价", exact: true }).click();
  await page.getByText("当前接口不提供持久草稿保存；离开页面不会保存未提交内容。", { exact: true }).waitFor();
  const times = page.locator(".dates input");
  await times.nth(0).fill("2099-01-01 00:00:00"); await times.nth(0).press("Enter");
  await times.nth(1).fill("2099-04-01 00:00:00"); await times.nth(1).press("Enter");
  await page.locator(".picker .el-select__wrapper").click();
  await page.getByRole("option").filter({ hasText: "gpt-4.1-mini" }).click();
  await page.getByRole("button", { name: "添加SKU", exact: true }).click();
  const priceInputs = page.locator(".sku-quote .el-table__body td:nth-child(4) input");
  await priceInputs.nth(0).fill("0.32"); await priceInputs.nth(1).fill("1.28");
  await page.getByLabel("整单倍率", { exact: true }).fill("0.8");
  await page.getByRole("button", { name: "应用整单倍率", exact: true }).click();
  await page.getByRole("button", { name: "确认应用", exact: true }).click();
  let submittedBody;
  page.on("request", request => { if (request.method() === "POST" && new URL(request.url()).pathname === "/api/supplier/quotes") submittedBody = request.postDataJSON(); });
  await page.getByRole("button", { name: "提交审批", exact: true }).click();
  await page.getByRole("button", { name: "确认提交", exact: true }).click();
  await page.getByRole("heading", { name: "报价历史", exact: true }).waitFor();
  assert.equal(submittedBody.items.length, 1); assert.equal(submittedBody.items[0].components.length, 2);
  assert.ok(!("model_name" in submittedBody.items[0])); assert.ok(!("currency" in submittedBody.items[0]));
  assert.ok(submittedBody.valid_to); assert.equal(submittedBody.items[0].fx_tier, "6.8");
  await page.getByRole("row").filter({ hasText: "6001" }).getByRole("button", { name: "查看详情", exact: true }).click();
  await page.getByRole("heading", { name: /审批中/ }).waitFor();
  await page.getByRole("button", { name: "关闭此对话框", exact: true }).click();
  await page.evaluate(() => { window.location.hash = "#/internal/supplier-quotes"; });
  await identity(page, "陈昊 · 采购审批");
  await page.getByRole("row").filter({ hasText: "云桥科技" }).getByRole("button", { name: "查看并审批", exact: true }).click();
  await page.getByRole("button", { name: "驳回", exact: true }).click();
  await page.getByPlaceholder("10—500字，说明供应商应如何复核").fill("浏览器确认新报价驳回后可再次提交新版本");
  await page.getByRole("button", { name: "确认驳回", exact: true }).click();
  await page.getByText("报价已驳回，原因供应商可见。", { exact: true }).waitFor();
  await page.evaluate(() => { window.location.hash = "#/supplier/quotes/import"; });
  const templateDownload = page.waitForEvent("download");
  await page.getByRole("button", { name: "下载CSV模板", exact: true }).click();
  const templateFile = await templateDownload;
  assert.ok((await readFile(await templateFile.path(), "utf8")).includes("official_input"));
  const importCsv = 'sku_id,sku_code,model_name,currency,fx_tier,price_input,price_output\n9007199254741001,gpt-4.1-mini,display only,USD,6.8,0.32,1.28';
  await page.locator('input[type="file"]').setInputFiles({ name: 'contract.csv', mimeType: 'text/csv', buffer: Buffer.from(importCsv) });
  await page.getByRole("button", { name: "开始预检", exact: true }).click();
  await page.getByText("总行数 1 · 通过 1 · 警告 0 · 错误 0", { exact: true }).waitFor();
  assert.equal(await page.getByRole("button", { name: "确认导入并生成草稿", exact: true }).count(), 0);
  const importTimes = page.locator(".import-panel .el-date-editor input");
  await importTimes.nth(0).fill("2099-01-01 00:00:00"); await importTimes.nth(0).press("Enter");
  await importTimes.nth(1).fill("2099-04-01 00:00:00"); await importTimes.nth(1).press("Enter");
  await page.locator(".import-panel article .el-table__body td:nth-child(2) input").first().fill("0.31");
  let confirmedImport;
  page.on("request", request => { if (request.method() === "POST" && new URL(request.url()).pathname === "/api/supplier/quotes/import/confirm") confirmedImport = request.postDataJSON(); });
  await page.getByRole("button", { name: "确认导入并提交审批", exact: true }).click();
  await page.getByRole("button", { name: "确认提交", exact: true }).click();
  await page.getByRole("heading", { name: "报价历史", exact: true }).waitFor();
  assert.equal(confirmedImport.items[0].components[0].unit_price,"0.31");
  assert.ok(!("currency" in confirmedImport.items[0])); assert.ok(!("token" in confirmedImport)); assert.ok(!("batchId" in confirmedImport));
  await page.getByRole("row").filter({ hasText: "6002" }).getByRole("button", { name: "查看详情", exact: true }).click();
  await page.getByRole("heading", { name: /审批中/ }).waitFor();

  await context.close(); await devServer.close(); devServer = undefined;

  // MSW disabled: the page reaches a local HTTP contract fixture through its real API module and Axios.
  const fakeKey = "sk-" + "synthetic-browser-key";
  const audit = { id: "audit-security", occurredAt: "2026-09-14T00:00:00Z", operatorName: "测试用户", operatorType: "USER", action: "安全展示验证", module: "模型", entityType: "MODEL", entityId: "test", result: "SUCCESS", source: "test", requestId: "test-request", before: { apiKey: fakeKey, nested: [{ password: "synthetic-password" }] }, after: { refresh_token: "synthetic-refresh" }, impact: [`Bearer ${fakeKey}`] };
  let received = 0;
  const backend = { name: "test-http-backend", configureServer(server) {
    server.middlewares.use((req, res, next) => {
      if (!req.url?.startsWith("/api/internal/audit-logs")) return next();
      received++;
      const path = req.url.split("?")[0];
      const data = path.endsWith("/export") ? { fileName: "audit.csv", content: `action,detail\nsecurity,api_key=${fakeKey}` }
        : path.endsWith("/audit-security") ? audit : { list: [audit], total: 1, page: 1, size: 5 };
      res.setHeader("Content-Type", "application/json"); res.end(JSON.stringify({ code: 0, data, requestId: "test" }));
    });
  } };
  const backendOrigin = await start(false, [backend]);
  const cleanContext = await browser.newContext({ serviceWorkers: "block", acceptDownloads: true });
  const cleanPage = await cleanContext.newPage(); track(cleanPage);
  await cleanPage.goto(`${backendOrigin}/#/internal/audit`);
  await cleanPage.getByText("安全展示验证", { exact: true }).waitFor();
  await cleanPage.getByRole("button", { name: "详情", exact: true }).first().click();
  await cleanPage.getByText("变更前", { exact: true }).waitFor();
  await cleanPage.locator(".audit-snapshots").getByText(/sk-\*{12}/).waitFor();
  const html = await cleanPage.locator("body").innerHTML();
  for (const raw of [fakeKey, "synthetic-password", "synthetic-refresh"]) assert.ok(!html.includes(raw));
  const storage = await cleanPage.evaluate(() => JSON.stringify({ local: { ...localStorage }, session: { ...sessionStorage } }));
  assert.ok(!storage.includes("synthetic"));
  await cleanPage.locator(".el-drawer__close-btn").click();
  const downloadPromise = cleanPage.waitForEvent("download");
  await cleanPage.getByRole("button", { name: /导出/ }).click();
  const download = await downloadPromise;
  const csv = await readFile(await download.path(), "utf8");
  assert.ok(!csv.includes(fakeKey));
  assert.ok(received >= 3);
  assert.equal(await cleanPage.evaluate(async () => (await navigator.serviceWorker.getRegistrations()).length), 0);
  await cleanContext.close();
  assert.deepEqual(errors, []);
  console.log("Browser checks passed: model actions, quote submit/history/rejection, CSV stream/preview/edit/confirm, theme, MSW-off HTTP audit path, credential DOM/storage/export masking.");
} finally {
  await browser.close();
  if (devServer) await devServer.close();
}
